projects:
  expoexampleamplify:
    schemaPath: ./graphql/schema.json
    includes:
      - ./graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: ./types/responses.ts
        docsFilePath: ./graphql/docs.md
