[build]
  command = "npm run build:web"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run preview"
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    "Content-Type" = "application/javascript"